services:
    fulcrum:
        image: docker.io/cculianu/fulcrum:v2.1.2
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "host.containers.internal:host-gateway"
        ports:
            - "50001:50001"
            - "50002:50002"
        volumes:
            - ./fulcrum:/data:U,Z
        entrypoint: >
            sh -c '
                set -e;
                mkdir -p /data/db;
                echo "
                datadir = /data/db
                bitcoind = ${BITCOIN_HOST}:${BITCOIN_RPC_PORT}
                rpcuser = ${BITCOIN_RPC_USER}
                rpcpassword = ${BITCOIN_RPC_PASS}
                tcp = 0.0.0.0:50001
                ssl = 0.0.0.0:50002
                peering = false
                announce = false
                " > /data/fulcrum.conf;

                exec /entrypoint.sh Fulcrum /data/fulcrum.conf;
            '
        restart: unless-stopped

    setup-datum-gateway:
        image: docker.io/alpine:3
        restart: "no"
        volumes:
            - ./datum:/datum:z
        entrypoint: >
            sh -c '
                set -e;
                apk add --no-cache jq wget;
                echo "📄 Preparing config.json...";

                if [ ! -f /datum/config.json ]; then
                    echo "⬇️ No config found, downloading default example...";
                    wget -qO /datum/config.json \
                        https://raw.githubusercontent.com/Retropex/datum-docker/main/settings/datum_gateway_config.json;
                fi
                jq \
                    ".bitcoind.rpcurl = \"${BITCOIN_HOST}:${BITCOIN_RPC_PORT}\" 
                    | .bitcoind.rpcuser = \"${BITCOIN_RPC_USER}\" 
                    | .bitcoind.rpcpassword = \"${BITCOIN_RPC_PASS}\" 
                    | .api.admin_password = \"${DATUM_ADMIN_PASS}\" 
                    | .api.modify_conf = true 
                    | .mining.pool_address = \"${DATUM_POOL_ADDRESS}\"" \
                    /datum/config.json > /datum/config.tmp && \
                    mv /datum/config.tmp /datum/config.json;
                echo "✅ Config written to /datum/config.json";
                cat /datum/config.json;
                echo "🔐 Setting permissions...";
                chown -R 1000:1000 /datum # datum user in the image
                echo "✅ Setup complete!";
                tail -f /dev/null;
            '

    datum-gateway:
        image: ghcr.io/retropex/datum:v1.14-blake2b-2@sha256:5895b55a5a1b8d76fbe49a6fbaaed3bdc98a847299e8b3107e631146faa6d58a
        command: ["./datum_gateway", "-c", "/app/config/config.json"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "host.containers.internal:host-gateway"
        ports:
            - "23334:23334"
            - "7152:7152"
        volumes:
            - ./datum:/app/config:z
            - ${BITCOIN_DATA}:/app/.bitcoin:ro
        restart: unless-stopped

    mempool-web:
        image: ghcr.io/retropex/mempoolfrontend:v3.4-beta3
        restart: unless-stopped
        stop_grace_period: 30s
        command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
        environment:
            FRONTEND_HTTP_PORT: "8998"
            BACKEND_MAINNET_HTTP_HOST: "mempool-api"
            AUDIT: "true"
        ports:
            - "8998:8998"

    mempool-api:
        image: ghcr.io/retropex/mempoolbackend:v3.4-beta3
        restart: unless-stopped
        stop_grace_period: 30s
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "host.containers.internal:host-gateway"
        ports:
            - "8999:8999"
        depends_on:
            - fulcrum
        command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
        environment:
            MEMPOOL_BACKEND: "electrum"
            ELECTRUM_HOST: "fulcrum"
            ELECTRUM_PORT: "50001"
            ELECTRUM_TLS_ENABLED: "false"
            CORE_RPC_HOST: "${BITCOIN_HOST}"
            CORE_RPC_PORT: "${BITCOIN_RPC_PORT}"
            CORE_RPC_USERNAME: "${BITCOIN_RPC_USER}"
            CORE_RPC_PASSWORD: "${BITCOIN_RPC_PASS}"
            DATABASE_ENABLED: "true"
            DATABASE_HOST: "mempool-db"
            DATABASE_DATABASE: "mempool"
            DATABASE_USERNAME: "mempool"
            DATABASE_PASSWORD: "mempool"
            STATISTICS_ENABLED: "true"
            MEMPOOL_BLOCKS_SUMMARIES_INDEXING: "true"
            MEMPOOL_GOGGLES_INDEXING: "true"
            MEMPOOL_AUDIT: "true"
        volumes:
            - ./mempool/backend/cache:/backend/cache:U,Z
            - ${BITCOIN_DATA}:/backend/.bitcoin:ro

    mempool-db:
        image: docker.io/mariadb:10.5.21
        restart: unless-stopped
        stop_grace_period: 30s
        environment:
            MYSQL_DATABASE: "mempool"
            MYSQL_USER: "mempool"
            MYSQL_PASSWORD: "mempool"
            MYSQL_ROOT_PASSWORD: "admin"
        volumes:
            - ./mempool/mysql:/var/lib/mysql:U,Z
